{% set name = "pymodulon" %}
{% set version = "0.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pymodulon-{{ version }}.tar.gz
  sha256: e082e06ed3487cba075972f3571d10e7ff60a3b29b3c9c75a8f23cea4d3044cf

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - adjusttext >=0.7
    - beautifulsoup4 >=4.9
    - biopython >=1.77
    - python-graphviz >=0.14
    - jupyter >=1.0
    - lxml >=4.6
    - matplotlib-base >=3.2
    - matplotlib-venn >=0.11
    - numpy >=1.19
    - openpyxl >=2.5
    - pandas >=1.0
    - python >=3.6
    - scikit-learn >=0.23
    - scipy >=1.5
    - seaborn >=0.10
    - statsmodels >=0.11
    - tqdm >=4.47

test:
  imports:
    - pymodulon
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/SBRG/pymodulon
  summary: Python package for analyzing and visualizing iModulons.
  dev_url: https://github.com/SBRG/pymodulon
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - avsastry
